openapi: 3.1.0
info:
  title: Brunei Datestamp and ICT Compliance API
  description: >
    Provides regulatory, ISO standards, and datestamp formatting metadata 
    for mobile app development and government ICT compliance in Brunei Darussalam.
  version: 1.0.0
servers:
  - url: https://snkatapbn.github.io/colorful-datestamp-api
    description: GitHub Pages static mock server

paths:
  /formats.json:
    get:
      operationId: getDateFormats
      summary: Get frontend and backend date formats (static)
      responses:
        '200':
          description: Static JSON with format info
          content:
            application/json:
              schema:
                type: object
                properties:
                  frontendFormat:
                    type: string
                    example: "dd-MM-yyyy"
                  backendFormat:
                    type: string
                    example: "yyyy-MM-dd"
components:
  schemas:
    DateFormats:
      type: object
      properties:
        frontendFormat:
          type: string
        backendFormat:
          type: string
      example:
        frontendFormat: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
        backendFormat: "YYYY-MM-DDTHH:mm:ss+08:00"

  /token:
    get:
      operationId: getGlobalToken
      summary: Get the global datestamp token used in UI
      responses:
        '200':
          description: Returns the response token string
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "@datestamp"

  /regulator:
    get:
      operationId: getRegulatorInfo
      summary: Get information about Brunei’s ICT regulator (AITI)
      responses:
        '200':
          description: National regulator info
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Authority for Info-communications Technology Industry
                  acronym:
                    type: string
                    example: AITI
                  jurisdiction:
                    type: string
                    example: Negara Brunei Darussalam
                  applicability:
                    type: array
                    items:
                      type: string
                    example:
                      - Mobile applications
                      - Digital government services
                      - ICT systems and platforms
                      - Data protection and cybersecurity

  /compliance/mobile:
    get:
      operationId: getMobileComplianceStandards
      summary: Get ISO standards for mobile development & privacy
      responses:
        '200':
          description: Lists mandatory ISO/IEC standards
          content:
            application/json:
              schema:
                type: object
                properties:
                  development:
                    type: array
                    items:
                      type: string
                    example:
                      - ISO/IEC 12207
                      - ISO/IEC 25010
                      - ISO/IEC 27034
                  privacy:
                    type: array
                    items:
                      type: string
                    example:
                      - ISO/IEC 27001
                      - ISO/IEC 27701
                      - ISO/IEC 27018



