openapi: 3.1.0
info:
  title: Brunei Datestamp and ICT Compliance API
  description: >
    Static JSON endpoints hosted on GitHub Pages providing Brunei datestamp token and
    official frontend/backend date format strings (including the colorful @datestamp prefix).
  version: 1.0.3

servers:
  - url: https://snkatapbn.github.io/colorful-datestamp-api
    description: GitHub Pages static server

paths:
  /formats.json:
    get:
      operationId: getDateFormats
      summary: Get frontend and backend date formats (colorful + official)
      responses:
        "200":
          description: Date format configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DateFormats"
              example:
                frontendFormat: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
                backendFormat: "YYYY-MM-DDTHH:mm:ss+08:00"

  /token.json:
    get:
      operationId: getGlobalToken
      summary: Get the global datestamp token
      responses:
        "200":
          description: Datestamp token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
              example:
                token: "@datestamp"

components:
  schemas:
    DateFormats:
      type: object
      additionalProperties: false
      required: [frontendFormat, backendFormat]
      properties:
        frontendFormat:
          type: string
          description: >
            Frontend/UI datestamp prefix + human-readable Brunei time format.
            Returned as a format string (not a rendered date).
          example: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
        backendFormat:
          type: string
          description: Backend/system exchange timestamp format string (UTC+08:00)
          example: "YYYY-MM-DDTHH:mm:ss+08:00"

    Token:
      type: object
      additionalProperties: false
      required: [token]
      properties:
        token:
          type: string
          description: Global response token
          example: "@datestamp"
openapi: 3.1.0
info:
  title: Brunei Datestamp and ICT Compliance API
  description: >
    Static JSON endpoints hosted on GitHub Pages providing Brunei datestamp token and
    official frontend/backend date format strings (including the colorful @datestamp prefix).
  version: 1.0.3

servers:
  - url: https://snkatapbn.github.io/colorful-datestamp-api
    description: GitHub Pages static server

paths:
  /formats.json:
    get:
      operationId: getDateFormats
      summary: Get frontend and backend date formats (colorful + official)
      responses:
        "200":
          description: Date format configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DateFormats"
              example:
                frontendFormat: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
                backendFormat: "YYYY-MM-DDTHH:mm:ss+08:00"

  /token.json:
    get:
      operationId: getGlobalToken
      summary: Get the global datestamp token
      responses:
        "200":
          description: Datestamp token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
              example:
                token: "@datestamp"

components:
  schemas:
    DateFormats:
      type: object
      additionalProperties: false
      required: [frontendFormat, backendFormat]
      properties:
        frontendFormat:
          type: string
          description: >
            Frontend/UI datestamp prefix + human-readable Brunei time format.
            Returned as a format string (not a rendered date).
          example: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
        backendFormat:
          type: string
          description: Backend/system exchange timestamp format string (UTC+08:00)
          example: "YYYY-MM-DDTHH:mm:ss+08:00"

    Token:
      type: object
      additionalProperties: false
      required: [token]
      properties:
        token:
          type: string
          description: Global response token
          example: "@datestamp"
openapi: 3.1.0
info:
  title: Brunei Datestamp and ICT Compliance API
  description: >
    Static JSON endpoints hosted on GitHub Pages providing Brunei datestamp token and
    official frontend/backend date format strings (including the colorful @datestamp prefix).
  version: 1.0.3

servers:
  - url: https://snkatapbn.github.io/colorful-datestamp-api
    description: GitHub Pages static server

paths:
  /formats.json:
    get:
      operationId: getDateFormats
      summary: Get frontend and backend date formats (colorful + official)
      responses:
        "200":
          description: Date format configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DateFormats"
              example:
                frontendFormat: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
                backendFormat: "YYYY-MM-DDTHH:mm:ss+08:00"

  /token.json:
    get:
      operationId: getGlobalToken
      summary: Get the global datestamp token
      responses:
        "200":
          description: Datestamp token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
              example:
                token: "@datestamp"

components:
  schemas:
    DateFormats:
      type: object
      additionalProperties: false
      required: [frontendFormat, backendFormat]
      properties:
        frontendFormat:
          type: string
          description: >
            Frontend/UI datestamp prefix + human-readable Brunei time format.
            Returned as a format string (not a rendered date).
          example: "@datestamp 📅 DD/MM/YYYY HH:mm (Brunei Time, BNT) | "
        backendFormat:
          type: string
          description: Backend/system exchange timestamp format string (UTC+08:00)
          example: "YYYY-MM-DDTHH:mm:ss+08:00"

    Token:
      type: object
      additionalProperties: false
      required: [token]
      properties:
        token:
          type: string
          description: Global response token
          example: "@datestamp"
